import { createStore } from 'vuex'

export default createStore({
  state: {
    Products: [
      {
        id: 1,
        piece: 1,
        name: "Lays's Yoğurt ve Mevsim Yeşillikli",
        price: 5,
        img: "https://lays.com.tr/uploads/assets/media/lays-yogurt-ve-mevsim-yesillikli.png",
      },
      {
        id: 2,
        piece: 1,
        name: "Lays's Baharatlı",
        price: 5,
        img: "https://lays.com.tr/uploads/assets/media/lays-baharatli.png",
      },
      {
        id: 3,
        piece: 1,
        name: "Lays's Klasik",
        price: 5,
        img: "https://lays.com.tr/uploads/assets/media/lays-klasik.png",
      },
      {
        id: 4,
        piece: 1,
        name: "Ruffles Originals",
        price: 6,
        img: "https://ruffles.com.tr/uploads/assets/media/ruffles-originals.png",
      },
      {
        id: 5,
        piece: 1,
        name: "Ruffles Ketçap",
        price: 6,
        img: "https://ruffles.com.tr/uploads/assets/media/ruffles-ketcap.png",
      },
      {
        id: 6,
        piece: 1,
        name: "Doritos Turca",
        price: 4.5,
        img: "https://umutmarket.com/wp-content/uploads/2020/12/turca.png",
      },
      {
        id: 7,
        piece: 1,
        name: "Doritos Nacho",
        price: 4.5,
        img: "https://doritos.com.tr/ResourcePackages/Bootstrap/assets/dist/images/products/nacho.png",
      },
      {
        id: 8,
        piece: 1,
        name: "Doritos Taco",
        price: 4.5,
        img: "https://images.marul.com/thumbs/016/0166755_doritos-taco-parti-boy-169-gr_320.png",
      },
      {
        id: 9,
        piece: 1,
        name: "Prigles",
        price: 7,
        img: "https://cdnd-tr.ceptesok.com/product/1000x1000/ac8c2_Original_Sade_Cips.png",
      },
      {
        id: 10,
        piece: 1,
        name: "Prigles Tortilla",
        price: 7,
        img: "https://migros-dali-storage-prod.global.ssl.fastly.net/macrocenter/product/05082543/05082543-619e57-1650x1650.png",
      },
      {
        id: 11,
        piece: 1,
        name: "Prigles Texas BBQ Sauce",
        price: 7,
        img: "https://www.aklife.co/content/images/default/barbecue_pringles_165g5a9e25ccf21f6.jpg",
      },
      {
        id: 12,
        piece: 1,
        name: "Patos Critos",
        price: 6,
        img: "https://dogusyiyecekicecek.com.tr/dist/assets/images/patos/slider/slider-img-4.png",
      },
      {
        id: 13,
        piece: 1,
        name: "Patos Acı Baharat Aromalı Hot Spice Flavour",
        price: 6,
        img: "https://patos.com.tr/wp-content/uploads/elementor/thumbs/patos-aci-baharat-p709mz7o2h67q11txoh378d3rbl4ptgw04xrrriy18.png",
      },
      {
        id: 14,
        piece: 1,
        name: "Patos Rolls Acılı",
        price: 6,
        img: "https://patos.com.tr/wp-content/uploads/elementor/thumbs/roll-p709mwe5hz2cr75xe597hr2pz5z12q5ozqzbbxn4jw.png",
      },
      {
        id: 15,
        piece: 1,
        name: "Çerezza Peynirli",
        price: 4,
        img: "https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05087052/05087052-27136c-1650x1650.png",
      },
      {
        id: 16,
        piece: 1,
        name: "Çerezza Mısırlı",
        price: 4,
        img: "https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05081717/05081717-10672d-1650x1650.png",
      },
    ],
  },
})
